import { Car, Users, Luggage, Star, Crown, Bus } from "lucide-react";

export const VEHICLE_CATEGORIES = {
	economy: {
		title: "Economy",
		description: "Budget-friendly options for everyday travel",
		icon: Car,
		gradient: "from-green-500 to-emerald-600",
		vehicles: [
			{
				id: "sedan",
				name: "Sedan",
				subtitle: "4+1 Seater",
				description:
					"Toyota Etios, Swift Dzire, Honda Xcent, Honda Amaze",
				pricing: {
					airport: "starting at ₹799",
					hourly4: "₹1,200",
					hourly8: "₹2,200",
					outstation: "₹12",
					driverBata: "₹400",
				},
				features: [
					"4+1 passengers",
					"AC Sedan",
					"Comfortable seating",
					"Luggage space",
				],
				icon: Users,
				images: [
					"/assets/cars/etios.png",
					"/assets/cars/sift-dezire.png",
					"/assets/cars/amaze.png",
				],
				popular: true,
				color: "from-blue-500 to-cyan-600",
			},
		],
	},
	suv: {
		title: "SUV",
		description: "Spacious vehicles for groups and families",
		icon: Luggage,
		gradient: "from-orange-500 to-red-600",
		vehicles: [
			{
				id: "suv",
				name: "SUV",
				subtitle: "6+1 to 7+1 Seater",
				description:
					"Maruti Ertiga, Toyota Innova, Kia Carens, Toyota Rumion",
				pricing: {
					airport: "₹1,499",
					hourly4: "₹1,600-1,900",
					hourly8: "₹2,800-3,200",
					outstation: "₹16-18",
					driverBata: "₹500",
				},
				features: [
					"6+1 to 7+1 passengers",
					"Spacious SUV",
					"Large luggage space",
					"Group travel",
				],
				icon: Luggage,
				images: [
					"/assets/cars/innova.png",
					"/assets/cars/ertiga.png",
					"/assets/cars/kia-carrens.png",
				],
				popular: true,
				color: "from-orange-500 to-red-600",
			},
		],
	},
	premium: {
		title: "Premium",
		description: "Enhanced comfort with premium vehicles",
		icon: Star,
		gradient: "from-purple-500 to-violet-600",
		vehicles: [
			{
				id: "prime-sedan",
				name: "Prime Sedan",
				subtitle: "4+1 Seater",
				description:
					"Maruti Ciaz, Platinum Etios, Nissan Sunny, Honda City",
				pricing: {
					airport: "starting at ₹899",
					hourly4: "₹1,300",
					hourly8: "₹2,400",
					outstation: "₹13-₹14",
					driverBata: "₹500",
				},
				features: [
					"4+1 passengers",
					"Premium sedan",
					"Enhanced comfort",
					"Premium interiors",
				],
				icon: Star,
				images: [
					"/assets/cars/ciaz.png",
					"/assets/cars/nissan-sunny.png",
					"/assets/cars/city.png",
				],
				popular: false,
				color: "from-purple-500 to-violet-600",
			},
			{
				id: "premium-suv",
				name: "Premium SUV",
				subtitle: "6+1 to 7+1 Seater",
				description: "Maruti Ertiga, Mahindra Marazzo, Toyota Rumion",
				pricing: {
					airport: "₹1,999-₹2,499",
					hourly4: "₹1,999-₹2,499",
					hourly8: "₹3,400-₹4,800",
					outstation: "₹19-₹24",
					driverBata: "₹600",
				},
				features: [
					"6+1 passengers",
					"Premium SUV",
					"Spacious interior",
					"Comfort ride",
				],
				icon: Luggage,
				images: [
					"/assets/cars/fortuner.png",
					"/assets/cars/innova-crysta.png",
					"/assets/cars/fortuner-black.png",
				],
				popular: true,
				color: "from-indigo-500 to-purple-600",
			},
		],
	},
	luxury: {
		title: "Luxury",
		description: "Premium luxury vehicles for special occasions",
		icon: Crown,
		gradient: "from-amber-500 to-yellow-600",
		vehicles: [
			{
				id: "premium-luxury",
				name: "Premium Luxury",
				subtitle: "4+1 Seater",
				description:
					"BMW 3 Series, Audi A4, Mercedes C-Class, Jaguar XE",
				pricing: {
					airport: "₹2,999-3,999",
					hourly4: "Not Available",
					hourly8: "₹5,999-7,999",
					outstation: "₹25-35",
					driverBata: "₹800",
				},
				features: [
					"4+1 passengers",
					"Luxury sedan",
					"Premium experience",
					"VIP treatment",
				],
				icon: Crown,
				images: [
					"/assets/cars/audi.png",
					"/assets/cars/bmw.png",
					"/assets/cars/mercedes.png",
				],
				popular: false,
				color: "from-yellow-500 to-amber-600",
			},
		],
	},
	group: {
		title: "Group Travel",
		description: "Large capacity vehicles for big groups",
		icon: Bus,
		gradient: "from-indigo-500 to-blue-600",
		vehicles: [
			{
				id: "tempo-traveller",
				name: "Tempo Traveller",
				subtitle: "12+1 Seater",
				description:
					"Spacious tempo traveller for large groups and events",
				pricing: {
					airport: "₹3,200-₹4,000",
					hourly4: "Not Available",
					hourly8: "₹4,199",
					outstation: "₹20-29",
					driverBata: "₹600",
				},
				features: [
					"12+1 passengers",
					"Large group travel",
					"Event transportation",
					"Ample luggage space",
				],
				icon: Bus,
				images: ["/assets/cars/traveller.png"],
				popular: false,
				color: "from-indigo-500 to-blue-600",
			},
		],
	},
};

export const DESTINATIONS = {
	bangalore: [
		{
			id: 1,
			name: "Lalbagh Botanical Garden",
			description:
				"Historic 240-acre garden with glasshouse and diverse plant species",
			image: "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
			distance: "15 km",
			duration: "45 mins",
			oneWay: "₹250",
			roundTrip: "₹450",
			category: "Nature",
			rating: 4.5,
			popular: true,
		},
		{
			id: 2,
			name: "Cubbon Park",
			description:
				"Green oasis in city center, perfect for jogging and relaxing",
			image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
			distance: "12 km",
			duration: "35 mins",
			oneWay: "₹200",
			roundTrip: "₹350",
			category: "Nature",
			rating: 4.3,
			popular: false,
		},
		{
			id: 3,
			name: "Bangalore Palace",
			description:
				"Majestic Tudor-style palace with elegant interiors and royal artifacts",
			image: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
			distance: "18 km",
			duration: "50 mins",
			oneWay: "₹300",
			roundTrip: "₹550",
			category: "Heritage",
			rating: 4.6,
			popular: true,
		},
		{
			id: 4,
			name: "ISKCON Temple",
			description: "Stunning white marble temple with spiritual ambiance",
			image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
			distance: "20 km",
			duration: "55 mins",
			oneWay: "₹350",
			roundTrip: "₹650",
			category: "Spiritual",
			rating: 4.7,
			popular: false,
		},
		{
			id: 5,
			name: "Wonderla Amusement Park",
			description:
				"Biggest amusement park with high-thrill rides and water slides",
			image: "https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
			distance: "25 km",
			duration: "1 hr",
			oneWay: "₹400",
			roundTrip: "₹750",
			category: "Entertainment",
			rating: 4.4,
			popular: true,
		},
	],
	weekend: [
		{
			id: 6,
			name: "Nandi Hills",
			description:
				"Scenic hill station with sunrise views and cycling trails",
			image: "/assets/destinations/nandi-hills.jpg",
			distance: "60 km",
			duration: "1.5 hrs",
			oneWay: "₹21,00",
			roundTrip: "₹3,300",
			category: "Hills",
			rating: 4.8,
			popular: true,
		},
		{
			id: 7,
			name: "Lepakshi temple",
			description: "Heritage site",
			image: "/assets/destinations/lepakshi-temple.png",
			distance: "127 km",
			duration: "2.5 hrs",
			oneWay: "₹21,00",
			roundTrip: "₹3,300",
			category: "Heritage",
			rating: 4.8,
			popular: true,
		},
		{
			id: 8,
			name: "Shivanasamudra Falls",
			description: "Breathtaking segmented waterfall on the Kaveri River",
			image: "/assets/destinations/shivana-samudra.png",
			distance: "130 km",
			duration: "2.5 hrs",
			oneWay: "₹2,799",
			roundTrip: "₹4,999",
			category: "Waterfalls",
			rating: 4.6,
			popular: true,
		},
		{
			id: 9,
			name: "Mysore",
			description: "Heritage city with grand palace and cultural charm",
			image: "/assets/destinations/mysore-palace.jpg",
			distance: "145 km",
			duration: "3 hrs",
			oneWay: "₹2,799",
			roundTrip: "₹5,100",
			category: "Heritage",
			rating: 4.9,
			popular: true,
		},
		{
			id: 10,
			name: "Isha foundation aadiyogi",
			description: "Heritage site with grand shiva statue",
			image: "/assets/destinations/isha-foundation.jpg",
			distance: "70 km",
			duration: "1.5 hrs",
			oneWay: "N/A",
			roundTrip: "₹3300",
			category: "Heritage",
			rating: 4.5,
			popular: false,
		},
	],
	extended: [
		{
			id: 11,
			name: "Chikmagalur",
			description:
				"Hill station with lush coffee plantations and trekking trails",
			image: "/assets/destinations/chickmagaluru.jpg",
			distance: "600 km",
			duration: "2 days",
			oneWay: "₹4,899",
			roundTrip: "₹9,400",
			category: "Coffee Estates",
			rating: 4.7,
			popular: true,
		},
		{
			id: 12,
			name: "Madikeri Coorg",
			description:
				"Scotland of India with misty hills and coffee estates",
			image: "/assets/destinations/coorg.jpg",
			distance: "600 km",
			duration: "2 days",
			oneWay: "₹4,999",
			roundTrip: "₹9,400",
			category: "Hills",
			rating: 4.8,
			popular: true,
		},
		{
			id: 13,
			name: "Ooty",
			description:
				"Charming hill station with colonial architecture and toy train",
			image: "/assets/destinations/ooty.jpg",
			distance: "600 km",
			duration: "2 days",
			oneWay: "₹5,200",
			roundTrip: "₹9,699",
			category: "Hills",
			rating: 4.6,
			popular: false,
		},
		{
			id: 14,
			name: "Wayanad",
			description:
				"Lush Kerala district with forests, waterfalls, and caves",
			image: "/assets/destinations/waynad.jpg",
			distance: "600 km",
			duration: "2 days",
			oneWay: "₹5,499",
			roundTrip: "₹10,500",
			category: "Nature",
			rating: 4.5,
			popular: false,
		},
		{
			id: 15,
			name: "Hogenakkal Falls",
			description:
				"Niagara of India with coracle rides and scenic beauty",
			image: "/assets/destinations/hogenakkal-falls.jpg",
			distance: "360 km",
			duration: "1 days",
			oneWay: "₹2,999",
			roundTrip: "₹5,199",
			category: "Waterfalls",
			rating: 4.4,
			popular: true,
		},
		{
			id: 16,
			name: "Chennai",
			description: "Beautiful city with pleasant beach.",
			image: "/assets/destinations/chennai.jpg",
			distance: "700 km",
			duration: "2 days",
			oneWay: "₹6,199",
			roundTrip: "₹10,900",
			category: "Beach",
			rating: 4.4,
			popular: true,
		},
	],
};
